[package]
name = "simd-r-drive-py"
version = "0.3.0-alpha.1"
edition = "2021"
publish = false # Python bindings only — do not publish to crates.io

[lib]
name = "simd_r_drive"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.0", features = ["extension-module"] }
simd-r-drive = { path = "../.." }
