[package]
name = "simd-r-drive-py"
version = "0.3.0-alpha.1"
edition = "2021"
description = "SIMD-optimized append-only schema-less storage engine. Key-based binary storage in a single-file storage container."
repository = "https://github.com/jzombie/rust-simd-r-drive"
license = "Apache-2.0"
categories = ["database-implementations", "data-structures", "filesystem"]
keywords = ["storage-engine", "binary-storage", "append-only", "simd", "mmap"]
publish = false # Python bindings only — do not publish to crates.io

[lib]
name = "simd_r_drive"
crate-type = ["cdylib"]

[dependencies]
memmap2 = "0.9.5"
pyo3 = { version = "0.25.0", features = ["extension-module"] }
simd-r-drive = { path = "../..", features = ["expose-internal-api"] }
