[package]
# See `pyproject.toml` for build artifact package info
name = "simd-r-drive-py-builder"
version = "0.4.1-alpha.9"
edition = "2021"
publish = false # Python bindings only — do not publish to crates.io

[lib]
name = "simd_r_drive"
crate-type = ["cdylib"]

[dependencies]
memmap2 = "0.9.5"
pyo3 = { version = "0.25.0", features = ["extension-module"] }
simd-r-drive = { path = "../..", features = ["expose-internal-api"] }
