[build-system]
requires = ["maturin>=1.5"]
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"
requires-python = ">=3.8"
include = [
    "simd_r_drive/__init__.py",
    "simd_r_drive/simd_r_drive.pyi",
    "simd_r_drive/py.typed"
]
