name: Build Python Wheels

on:
  push:
    paths:
      - "bindings/python/**"
  pull_request:
    paths:
      - "bindings/python/**"

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tooling from requirements.txt
        run: pip install -r bindings/python/requirements.txt

      - name: Build wheels
        env:
          CIBW_SKIP: "cp36-* cp37-* cp38-* cp39-* pp* *-manylinux_i686 *-musllinux_*"
        run: cibuildwheel bindings/python --output-dir bindings/python/dist

      - name: Install built wheel and run tests
        run: |
          python -c "import sys, glob, subprocess; \
            ver = f'cp{sys.version_info[0]}{sys.version_info[1]}'; \
            whl = glob.glob(f'bindings/python/dist/*{ver}*.whl')[0]; \
            subprocess.run(['pip', 'install', whl], check=True)"
          pytest bindings/python/tests

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: simd_r_drive_py-wheels-${{ matrix.os }}
          path: bindings/python/dist/*.whl
